In [ ]:
# import json
# import openml
# from tqdm import tqdm

# catalog = openml.datasets.list_datasets(output_format="dataframe")

# all_metadata = []

# for did in tqdm(catalog["did"]):
#     try:
#         ds = openml.datasets.get_dataset(
#             did,
#             download_data=False,
#         )

#         metadata = {}

#         for key, value in vars(ds).items():
#             try:
#                 json.dumps(value)
#                 metadata[key] = value
#             except TypeError:
#                 metadata[key] = str(value)

#         all_metadata.append(metadata)

#     except Exception as e:
#         print(f"Failed {did}: {e}")

# with open("openml_raw_metadata.json", "w", encoding="utf-8") as f:
#     json.dump(all_metadata, f, indent=2, ensure_ascii=False)

100%|██████████| 6408/6408 [38:13<00:00,  2.79it/s]

In [148]:
import json
import pandas as pd

df = pd.DataFrame(all_metadata)
df.to_csv("openml_raw_metadata.csv", index=False)

In [12]:
df.columns

Index(['ignore_attribute', 'dataset_id', 'name', 'version', 'description',
       'cache_format', 'format', 'creator', 'contributor', 'collection_date',
       'upload_date', 'language', 'licence', 'url', 'default_target_attribute',
       'row_id_attribute', 'version_label', 'citation', 'tag', 'visibility',
       'original_data_url', 'paper_url', 'md5_checksum', '_parquet_url',
       '_no_qualities_found'],
      dtype='object')

In [11]:
# Drops columns where EVERY value is NaN/None
df = df.dropna(axis=1, how="all")

In [31]:
df.ignore_attribute[0]

In [48]:
def print_unique_counts(df):
    data_vals = {}
    for col in df.columns:
        try:
            unique_count = df[col].astype(str).nunique(dropna=False)
            print(f"{col}: {unique_count}")
            data_vals[col] = unique_count
        except Exception as e:
            print(f"{col}: ERROR ({e})")
    return data_vals

In [49]:
get_vals = print_unique_counts(df)

ignore_attribute: 181
dataset_id: 6408
name: 5002
version: 52
description: 4729
cache_format: 1
format: 4
creator: 754
contributor: 139
collection_date: 1001
upload_date: 6382
language: 22
licence: 185
url: 6386
default_target_attribute: 755
row_id_attribute: 53
version_label: 487
citation: 645
tag: 1112
visibility: 1
original_data_url: 1835
paper_url: 289
md5_checksum: 5936
_parquet_url: 5261
_no_qualities_found: 1

In [62]:
df["default_target_attribute"].sample(20)

4135           price
6124         biopsed
4468     binaryClass
1940    MEDIAN_PXC50
1365    MEDIAN_PXC50
6064      fraud_bool
742      binaryClass
1358    MEDIAN_PXC50
2520           class
5823     risk_rating
5308          Exited
4708           class
4842        IsBadBuy
2021    MEDIAN_PXC50
1655    MEDIAN_PXC50
5059            None
2698           Class
2223    MEDIAN_PXC50
2007    MEDIAN_PXC50
130            price
Name: default_target_attribute, dtype: object

In [170]:
df[df["name"]=="bridges"]["tag"]

217           [Civil Engineering, Machine Learning, uci]
218                                                 None
849    [Environment, Geography, mythbusting_1, Statis...
Name: tag, dtype: object

In [169]:
df[df["version"]==4]#["tag"]

,ignore_attribute,dataset_id,name,version,description,cache_format,format,creator,contributor,collection_date,...,data_file,parquet_file,_dataset,_parquet_url,_features,_qualities,_no_qualities_found,data_pickle_file,data_feather_file,feather_attribute_file
218,None,328,bridges,4,"**Author**: Yoram Reich"",""Steven J. Fenves \n...",pickle,ARFF,"[Yoram Reich, Steven J. Fenves]",None,1990-08-01,...,None,None,None,https://data.openml.org/datasets/0000/0328/dat...,None,None,False,None,None,None
1041,None,1219,Click_prediction_small,4,**Author**: Tencent Inc. \n**Source**: [KDD C...,pickle,ARFF,None,None,None,...,None,None,None,https://data.openml.org/datasets/0000/1219/dat...,None,None,False,None,None,None
1273,None,1596,covertype,4,"**Author**: Jock A. Blackard, Dr. Denis J. Dea...",pickle,ARFF,None,None,None,...,None,None,None,https://data.openml.org/datasets/0000/1596/dat...,None,None,False,None,None,None
2401,None,23397,COMET_MC_SAMPLE,4,Sample with OpenML metadata.,pickle,ARFF,None,None,None,...,None,None,None,https://data.openml.org/datasets/0002/23397/da...,None,None,False,None,None,None
2402,None,23420,yagoSchema.ttl,4,YAGO Schema.,pickle,ARFF,None,None,None,...,None,None,None,https://data.openml.org/datasets/0002/23420/da...,None,None,False,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6242,None,46999,Cervical_Cancer_Risk_Factors,4,Cervical cancer (Risk Factors) Data Set (multi...,pickle,arff,"Kelwin Fernandes, Jaime S. Cardoso, Jessica Fe...",Israel Campero Jurado,01-03-2025,...,None,None,None,https://data.openml.org/datasets/0004/46999/da...,None,None,False,None,None,None
6246,None,47003,melbourne_airbnb,4,Predict the price label of AirBnb listings (in...,pickle,arff,"Xingjian Shi, Jonas Mueller, Nick Erickson, Mu...",Israel Campero Jurado,19-02-2025,...,None,None,None,https://data.openml.org/datasets/0004/47003/da...,None,None,False,None,None,None
6263,None,47024,Laboratorio_dataset_car,4,actividad 1 machine learning,pickle,arff,Emmanuel Mouret,Mouret,01062025,...,None,None,None,https://data.openml.org/datasets/0004/47024/da...,None,None,False,None,None,None
6285,None,47047,Accidents_Prediction_Dataset,4,Mining safety dataset for predicting accidents,pickle,arff,Your Name,Budibase Integration,2025-10-04,...,None,None,None,https://data.openml.org/datasets/0004/47047/da...,None,None,False,None,None,None
6370,None,47145,dummy_edit_test_dataset_ipynb,4,Notebook Test Dataset,pickle,arff,Updated Creator,None,2024-01-01,...,None,None,None,https://data.openml.org/datasets/0004/47145/da...,None,None,False,None,None,None

In [96]:
def clean_tags(tags):
    if tags != None:
        return [
            tag for tag in tags
            if not tag.startswith("study_")
        ]

In [152]:
df["tag"].isna().sum()

np.int64(3558)

In [150]:
df["tag"].tail(20)

6388          None
6389          None
6390    normal_tag
6391          None
6392          None
6393          None
6394          None
6395          None
6396          None
6397          None
6398          None
6399          None
6400          None
6401          None
6402          None
6403          None
6404          None
6405          None
6406          None
6407          None
Name: tag, dtype: object

In [63]:
def dataset_to_text(row):
    parts = [
        f"Dataset: {row['name']}",
        f"Description: {row['description']}",
        f"Tags: {', '.join(row['tag']) if isinstance(row['tag'], list) else row['tag']}",
        f"Target: {row['default_target_attribute']}",
        f"Language: {row['language']}",
        f"Creator: {row['creator']}",
    ]
    return "\n".join(str(x) for x in parts if x and str(x) != "nan")

In [64]:
df["embedding_text"] = df.apply(dataset_to_text, axis=1)

In [65]:
df["embedding_text"].sample(5, random_state=42).tolist()

['Dataset: Climate\nDescription: This file holds global land temperatures by country\nTags: None\nTarget: None\nLanguage: None\nCreator: None',
 'Dataset: GPT-Tweets\nDescription: raw tweets on ChatGPT\nTags: None\nTarget: None\nLanguage: None\nCreator: -',
 'Dataset: COMET_MC_SAMPLE\nDescription: Another sample of COMET_MC\nTags: None\nTarget: label\nLanguage: None\nCreator: None',
 'Dataset: QSAR-TID-101097\nDescription: **Author**: Dr Ivan Olier, Dr Jeremy Besnard, Dr Noureddin Sadawi, Dr Larisa Soldatova, Dr Crina Grosan, Prof Ross King, Dr Richard Bickerton, Prof Andrew Hopkins and Dr Willem van Hoorn  \n**Source**: MetaQSAR project - September 2015  \n**Please cite**:   \n\nThis dataset contains QSAR data (from ChEMBL version 17) showing activity values (unit is pseudo-pCI50) of several compounds on drug target TID: 101097, and it has 59 rows and 1026 features (including IDs and class feature: MOLECULE_CHEMBL_ID and MEDIAN_PXC50). The features represent FCFP 1024bit Molecular Fingerprints which were generated from SMILES strings. They were obtained using the Pipeline Pilot program, Dassault Systèmes BIOVIA. Generating Fingerprints does not usually require missing value imputation as all bits are generated.\nTags: Biology, Chemistry, MTLQSAR, Pharmacology, Research, study_3\nTarget: MEDIAN_PXC50\nLanguage: None\nCreator: Dr Jeremy Besnard, Dr Ivan Olier, Dr Noureddin Sadawi, Dr Larisa Soldatova, Dr Crina Grosan, Prof Ross King, Dr Richard Bickerton, Prof Andrew Hopkins and Dr Willem van Hoorn',
 'Dataset: Colon\nDescription: **Colon dataset**\n\n**Authors**: U. Alon, N. Barkai, D. Notterman, K. Gish, S. Ybarra, D. Mack, A. Levine\n\n**Please cite**: ([URL](https://www.pnas.org/doi/abs/10.1073/pnas.96.12.6745)): U. Alon, N. Barkai, D. Notterman, K. Gish, S. Ybarra, D. Mack, A. Levine, Broad patterns of gene expression revealed by clustering analysis of tumor and normal colon tissues probed by oligonucleotide arrays, Proc. Nat. Acad. Sci. 96 (12) (1999) 6745-6750\nTags: Biotechnology, Genetics, Health, Medicine, microarray, Oncology\nTarget: class\nLanguage: None\nCreator: U. Alon, N. Barkai, D. Notterman, K. Gish, S. Ybarra, D. Mack, A. Levine']

In [66]:
model_MiniLM = SentenceTransformer(
    "all-MiniLM-L6-v2"
    )

embeddings = model_MiniLM.encode(
    df["embedding_text"].tolist(),
    show_progress_bar=True
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

Batches:   0%|          | 0/201 [00:00<?, ?it/s]

In [ ]:
def recommend(idx, pred_matrix=embeddings, top_k=10):

    scores = list(enumerate(pred_matrix[idx]))
    scores = sorted(scores, key=lambda x: x[1], reverse=True)

    top = scores[1:top_k+1]

    indices = [i for i, _ in top]

    
    return pd.DataFrame({
        "idx": indices,
        "name": df.iloc[indices]["name"].values,
        "description": df.iloc[indices]["description"].values,
        "tag": df.iloc[indices]["tag"].values,
        
    })

In [158]:
print(df.iloc[26])

ignore_attribute                                                         None
dataset_id                                                                 31
name                                                                 credit-g
version                                                                     1
description                 **Author**: Dr. Hans Hofmann  \n**Source**: [U...
cache_format                                                           pickle
format                                                                   ARFF
creator                                                      Dr. Hans Hofmann
contributor                                                              None
collection_date                                                    1994-11-17
upload_date                                               2014-04-06T23:21:47
language                                                              English
licence                                                                Public
url                         https://openml.org/data/v1/download/31/credit-...
default_target_attribute                                                class
row_id_attribute                                                         None
version_label                                                               1
citation                    https://archive.ics.uci.edu/ml/citation_policy...
tag                         [credit_scoring, Data Science, Economics, fina...
visibility                                                             public
original_data_url           https://archive.ics.uci.edu/ml/datasets/statlo...
paper_url                    https://dl.acm.org/doi/abs/10.1145/967900.968104
update_comment                                                           None
md5_checksum                                 9a475053fed0c26ee95cd4525e50074c
data_file                                                                None
parquet_file                                                             None
_dataset                                                                 None
_parquet_url                https://data.openml.org/datasets/0000/0031/dat...
_features                                                                None
_qualities                                                               None
_no_qualities_found                                                     False
data_pickle_file                                                         None
data_feather_file                                                        None
feather_attribute_file                                                   None
Name: 26, dtype: object

In [156]:
recommend(26)

,idx,name,description,tag
0,277,siddiqi,**Author**: \n**Source**: Unknown - Date unk...,None
1,177,BNG(colic.ORIG),None,"[Animal Health, artificial, Data Analysis, Med..."
2,31,diabetes,**Author**: [Vincent Sigillito](vgs@aplcen.apl...,"[Health, Kaggle, mythbusting_1, Nutrition, Ope..."
3,306,qsbr_rw1,**Author**: \n**Source**: Unknown - Date unk...,None
4,307,analcatdata_broadway,**Author**: \n**Source**: Unknown - Date unk...,"[Arts, Culture, Data Science, study_1]"
5,193,IMDB.drama,"**Author**: Read, Jesse and Bifet, Albert an...","[concept_drift, Entertainment, Machine Learnin..."
6,183,BNG(cylinder-bands),None,"[artificial, Engineering, Manufacturing, Mater..."
7,214,spectrometer,**Author**: \n \n**Source**: Unknown - 1988...,"[Astrophysics, study_1, study_7, uci]"
8,373,analcatdata_gviolence,**Author**: \n**Source**: Unknown - Date unk...,None
9,10,mfeat-factors,"**Author**: Robert P.W. Duin, Department of Ap...","[OpenML-CC18, OpenML100, Pattern Recognition, ..."